# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2020-08-15 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default='', max_length=100),
        ),
    ]
